"""
地理词典 — 城市/省份/国家 中英文对照
从已有 DB 数据 + 手动扩充
"""

# ============================================================
# 中国城市 → (city_en, country_cn, country_en)
# 按名称长度降序排列（贪婪匹配用）
# ============================================================
CN_CITIES = {
    "呼和浩特": ("Hohhot", "中国", "China"),
    "哈尔滨": ("Harbin", "中国", "China"),
    "石家庄": ("Shijiazhuang", "中国", "China"),
    "乌鲁木齐": ("Urumqi", "中国", "China"),
    "连云港": ("Lianyungang", "中国", "China"),
    "秦皇岛": ("Qinhuangdao", "中国", "China"),
    "张家界": ("Zhangjiajie", "中国", "China"),
    "景德镇": ("Jingdezhen", "中国", "China"),
    "驻马店": ("Zhumadian", "中国", "China"),
    "佳木斯": ("Jiamusi", "中国", "China"),
    "齐齐哈尔": ("Qiqihar", "中国", "China"),
    "攀枝花": ("Panzhihua", "中国", "China"),
    "武夷山": ("Wuyishan", "中国", "China"),
    "张家口": ("Zhangjiakou", "中国", "China"),
    "西双版纳": ("Xishuangbanna", "中国", "China"),
    "香格里拉": ("Shangri-La", "中国", "China"),
    "上海": ("Shanghai", "中国", "China"),
    "北京": ("Beijing", "中国", "China"),
    "广州": ("Guangzhou", "中国", "China"),
    "深圳": ("Shenzhen", "中国", "China"),
    "成都": ("Chengdu", "中国", "China"),
    "重庆": ("Chongqing", "中国", "China"),
    "天津": ("Tianjin", "中国", "China"),
    "杭州": ("Hangzhou", "中国", "China"),
    "南京": ("Nanjing", "中国", "China"),
    "武汉": ("Wuhan", "中国", "China"),
    "西安": ("Xi'an", "中国", "China"),
    "郑州": ("Zhengzhou", "中国", "China"),
    "沈阳": ("Shenyang", "中国", "China"),
    "青岛": ("Qingdao", "中国", "China"),
    "大连": ("Dalian", "中国", "China"),
    "宁波": ("Ningbo", "中国", "China"),
    "厦门": ("Xiamen", "中国", "China"),
    "济南": ("Jinan", "中国", "China"),
    "长沙": ("Changsha", "中国", "China"),
    "福州": ("Fuzhou", "中国", "China"),
    "合肥": ("Hefei", "中国", "China"),
    "昆明": ("Kunming", "中国", "China"),
    "苏州": ("Suzhou", "中国", "China"),
    "无锡": ("Wuxi", "中国", "China"),
    "南昌": ("Nanchang", "中国", "China"),
    "贵阳": ("Guiyang", "中国", "China"),
    "南宁": ("Nanning", "中国", "China"),
    "太原": ("Taiyuan", "中国", "China"),
    "长春": ("Changchun", "中国", "China"),
    "兰州": ("Lanzhou", "中国", "China"),
    "海口": ("Haikou", "中国", "China"),
    "银川": ("Yinchuan", "中国", "China"),
    "西宁": ("Xining", "中国", "China"),
    "拉萨": ("Lhasa", "中国", "China"),
    "珠海": ("Zhuhai", "中国", "China"),
    "佛山": ("Foshan", "中国", "China"),
    "东莞": ("Dongguan", "中国", "China"),
    "温州": ("Wenzhou", "中国", "China"),
    "台州": ("Taizhou", "中国", "China"),
    "烟台": ("Yantai", "中国", "China"),
    "威海": ("Weihai", "中国", "China"),
    "潍坊": ("Weifang", "中国", "China"),
    "临沂": ("Linyi", "中国", "China"),
    "淄博": ("Zibo", "中国", "China"),
    "绍兴": ("Shaoxing", "中国", "China"),
    "嘉兴": ("Jiaxing", "中国", "China"),
    "金华": ("Jinhua", "中国", "China"),
    "义乌": ("Yiwu", "中国", "China"),
    "湖州": ("Huzhou", "中国", "China"),
    "南通": ("Nantong", "中国", "China"),
    "徐州": ("Xuzhou", "中国", "China"),
    "常州": ("Changzhou", "中国", "China"),
    "镇江": ("Zhenjiang", "中国", "China"),
    "扬州": ("Yangzhou", "中国", "China"),
    "泰州": ("Taizhou2", "中国", "China"),
    "盐城": ("Yancheng", "中国", "China"),
    "淮安": ("Huai'an", "中国", "China"),
    "宿迁": ("Suqian", "中国", "China"),
    "中山": ("Zhongshan", "中国", "China"),
    "惠州": ("Huizhou", "中国", "China"),
    "江门": ("Jiangmen", "中国", "China"),
    "湛江": ("Zhanjiang", "中国", "China"),
    "汕头": ("Shantou", "中国", "China"),
    "揭阳": ("Jieyang", "中国", "China"),
    "肇庆": ("Zhaoqing", "中国", "China"),
    "清远": ("Qingyuan", "中国", "China"),
    "梅州": ("Meizhou", "中国", "China"),
    "茂名": ("Maoming", "中国", "China"),
    "阳江": ("Yangjiang", "中国", "China"),
    "韶关": ("Shaoguan", "中国", "China"),
    "潮州": ("Chaozhou", "中国", "China"),
    "河源": ("Heyuan", "中国", "China"),
    "云浮": ("Yunfu", "中国", "China"),
    "汕尾": ("Shanwei", "中国", "China"),
    "洛阳": ("Luoyang", "中国", "China"),
    "南阳": ("Nanyang", "中国", "China"),
    "新乡": ("Xinxiang", "中国", "China"),
    "安阳": ("Anyang", "中国", "China"),
    "许昌": ("Xuchang", "中国", "China"),
    "信阳": ("Xinyang", "中国", "China"),
    "开封": ("Kaifeng", "中国", "China"),
    "焦作": ("Jiaozuo", "中国", "China"),
    "平顶山": ("Pingdingshan", "中国", "China"),
    "商丘": ("Shangqiu", "中国", "China"),
    "濮阳": ("Puyang", "中国", "China"),
    "周口": ("Zhoukou", "中国", "China"),
    "漯河": ("Luohe", "中国", "China"),
    "鹤壁": ("Hebi", "中国", "China"),
    "三门峡": ("Sanmenxia", "中国", "China"),
    "唐山": ("Tangshan", "中国", "China"),
    "保定": ("Baoding", "中国", "China"),
    "廊坊": ("Langfang", "中国", "China"),
    "邯郸": ("Handan", "中国", "China"),
    "沧州": ("Cangzhou", "中国", "China"),
    "邢台": ("Xingtai", "中国", "China"),
    "衡水": ("Hengshui", "中国", "China"),
    "承德": ("Chengde", "中国", "China"),
    "包头": ("Baotou", "中国", "China"),
    "鄂尔多斯": ("Ordos", "中国", "China"),
    "赤峰": ("Chifeng", "中国", "China"),
    "柳州": ("Liuzhou", "中国", "China"),
    "桂林": ("Guilin", "中国", "China"),
    "北海": ("Beihai", "中国", "China"),
    "三亚": ("Sanya", "中国", "China"),
    "绵阳": ("Mianyang", "中国", "China"),
    "德阳": ("Deyang", "中国", "China"),
    "宜宾": ("Yibin", "中国", "China"),
    "泸州": ("Luzhou", "中国", "China"),
    "遵义": ("Zunyi", "中国", "China"),
    "曲靖": ("Qujing", "中国", "China"),
    "宝鸡": ("Baoji", "中国", "China"),
    "咸阳": ("Xianyang", "中国", "China"),
    "榆林": ("Yulin", "中国", "China"),
    "天水": ("Tianshui", "中国", "China"),
    "宜昌": ("Yichang", "中国", "China"),
    "襄阳": ("Xiangyang", "中国", "China"),
    "荆州": ("Jingzhou", "中国", "China"),
    "黄石": ("Huangshi", "中国", "China"),
    "株洲": ("Zhuzhou", "中国", "China"),
    "湘潭": ("Xiangtan", "中国", "China"),
    "岳阳": ("Yueyang", "中国", "China"),
    "衡阳": ("Hengyang", "中国", "China"),
    "郴州": ("Chenzhou", "中国", "China"),
    "常德": ("Changde", "中国", "China"),
    "九江": ("Jiujiang", "中国", "China"),
    "赣州": ("Ganzhou", "中国", "China"),
    "上饶": ("Shangrao", "中国", "China"),
    "吉安": ("Ji'an", "中国", "China"),
    "宜春": ("Yichun", "中国", "China"),
    "芜湖": ("Wuhu", "中国", "China"),
    "蚌埠": ("Bengbu", "中国", "China"),
    "马鞍山": ("Ma'anshan", "中国", "China"),
    "安庆": ("Anqing", "中国", "China"),
    "阜阳": ("Fuyang", "中国", "China"),
    "滁州": ("Chuzhou", "中国", "China"),
    "六安": ("Lu'an", "中国", "China"),
    "菏泽": ("Heze", "中国", "China"),
    "济宁": ("Jining", "中国", "China"),
    "东营": ("Dongying", "中国", "China"),
    "聊城": ("Liaocheng", "中国", "China"),
    "德州": ("Dezhou", "中国", "China"),
    "枣庄": ("Zaozhuang", "中国", "China"),
    "日照": ("Rizhao", "中国", "China"),
    "滨州": ("Binzhou", "中国", "China"),
    "泰安": ("Tai'an", "中国", "China"),
    "龙岩": ("Longyan", "中国", "China"),
    "南平": ("Nanping", "中国", "China"),
    "三明": ("Sanming", "中国", "China"),
    "莆田": ("Putian", "中国", "China"),
    "泉州": ("Quanzhou", "中国", "China"),
    "漳州": ("Zhangzhou", "中国", "China"),
    "宁德": ("Ningde", "中国", "China"),
    "延边": ("Yanbian", "中国", "China"),
    "吉林市": ("Jilin City", "中国", "China"),
    "大庆": ("Daqing", "中国", "China"),
    "牡丹江": ("Mudanjiang", "中国", "China"),
    "延吉": ("Yanji", "中国", "China"),
    "鞍山": ("Anshan", "中国", "China"),
    "抚顺": ("Fushun", "中国", "China"),
    "锦州": ("Jinzhou", "中国", "China"),
    "营口": ("Yingkou", "中国", "China"),
    "丹东": ("Dandong", "中国", "China"),
    "盘锦": ("Panjin", "中国", "China"),
    "本溪": ("Benxi", "中国", "China"),
    "朝阳": ("Chaoyang", "中国", "China"),
    "铁岭": ("Tieling", "中国", "China"),
    "葫芦岛": ("Huludao", "中国", "China"),
    "大同": ("Datong", "中国", "China"),
    "阳泉": ("Yangquan", "中国", "China"),
    "长治": ("Changzhi", "中国", "China"),
    "晋城": ("Jincheng", "中国", "China"),
    "朔州": ("Shuozhou", "中国", "China"),
    "运城": ("Yuncheng", "中国", "China"),
    "吕梁": ("Lvliang", "中国", "China"),
    "晋中": ("Jinzhong", "中国", "China"),
    "临汾": ("Linfen", "中国", "China"),
    "忻州": ("Xinzhou", "中国", "China"),
    "永康": ("Yongkang", "中国", "China"),
    "慈溪": ("Cixi", "中国", "China"),
    "余姚": ("Yuyao", "中国", "China"),
    "诸暨": ("Zhuji", "中国", "China"),
    "温岭": ("Wenling", "中国", "China"),
    "乐清": ("Yueqing", "中国", "China"),
    "瑞安": ("Rui'an", "中国", "China"),
    "海宁": ("Haining", "中国", "China"),
    "桐乡": ("Tongxiang", "中国", "China"),
    "晋江": ("Jinjiang", "中国", "China"),
    "南安": ("Nan'an", "中国", "China"),
    "滕州": ("Tengzhou", "中国", "China"),
    "寿光": ("Shouguang", "中国", "China"),
    "诸城": ("Zhucheng", "中国", "China"),
    "莱西": ("Laixi", "中国", "China"),
    "胶州": ("Jiaozhou", "中国", "China"),
    "即墨": ("Jimo", "中国", "China"),
    "平度": ("Pingdu", "中国", "China"),
    "荣成": ("Rongcheng", "中国", "China"),
    "乳山": ("Rushan", "中国", "China"),
    "蓬莱": ("Penglai", "中国", "China"),
    "招远": ("Zhaoyuan", "中国", "China"),
    "栖霞": ("Qixia", "中国", "China"),
    "海阳": ("Haiyang", "中国", "China"),
    "青州": ("Qingzhou", "中国", "China"),
    "曲阜": ("Qufu", "中国", "China"),
    "新泰": ("Xintai", "中国", "China"),
    "肥城": ("Feicheng", "中国", "China"),
    "邹城": ("Zoucheng", "中国", "China"),
    "港澳": ("Hong Kong/Macau", "中国", "China"),
    "香港": ("Hong Kong", "中国", "China"),
    "澳门": ("Macau", "中国", "China"),
    "台湾": ("Taiwan", "中国", "China"),
    "台北": ("Taipei", "中国", "China"),
    "高雄": ("Kaohsiung", "中国", "China"),
    "台中": ("Taichung", "中国", "China"),
    "台南": ("Tainan", "中国", "China"),
    "桃园": ("Taoyuan", "中国", "China"),
}

# ============================================================
# 中国省份/自治区（用于名称匹配，但 city 字段写省份名）
# ============================================================
CN_PROVINCES = {
    "新疆": ("Xinjiang", "中国", "China"),
    "西藏": ("Tibet", "中国", "China"),
    "内蒙古": ("Inner Mongolia", "中国", "China"),
    "广西": ("Guangxi", "中国", "China"),
    "宁夏": ("Ningxia", "中国", "China"),
    "浙江": ("Zhejiang", "中国", "China"),
    "江苏": ("Jiangsu", "中国", "China"),
    "广东": ("Guangdong", "中国", "China"),
    "山东": ("Shandong", "中国", "China"),
    "福建": ("Fujian", "中国", "China"),
    "四川": ("Sichuan", "中国", "China"),
    "湖北": ("Hubei", "中国", "China"),
    "湖南": ("Hunan", "中国", "China"),
    "河南": ("Henan", "中国", "China"),
    "河北": ("Hebei", "中国", "China"),
    "辽宁": ("Liaoning", "中国", "China"),
    "陕西": ("Shaanxi", "中国", "China"),
    "山西": ("Shanxi", "中国", "China"),
    "江西": ("Jiangxi", "中国", "China"),
    "安徽": ("Anhui", "中国", "China"),
    "云南": ("Yunnan", "中国", "China"),
    "贵州": ("Guizhou", "中国", "China"),
    "甘肃": ("Gansu", "中国", "China"),
    "吉林": ("Jilin", "中国", "China"),
    "海南": ("Hainan", "中国", "China"),
    "青海": ("Qinghai", "中国", "China"),
    "黑龙江": ("Heilongjiang", "中国", "China"),
}

# ============================================================
# 外国城市 → (city_en, country_cn, country_en)
# ============================================================
FOREIGN_CITIES = {
    # 阿联酋
    "迪拜": ("Dubai", "阿联酋", "UAE"),
    "阿布扎比": ("Abu Dhabi", "阿联酋", "UAE"),
    "沙迦": ("Sharjah", "阿联酋", "UAE"),
    # 德国
    "法兰克福": ("Frankfurt", "德国", "Germany"),
    "慕尼黑": ("Munich", "德国", "Germany"),
    "柏林": ("Berlin", "德国", "Germany"),
    "杜塞尔多夫": ("Dusseldorf", "德国", "Germany"),
    "科隆": ("Cologne", "德国", "Germany"),
    "汉诺威": ("Hanover", "德国", "Germany"),
    "斯图加特": ("Stuttgart", "德国", "Germany"),
    "汉堡": ("Hamburg", "德国", "Germany"),
    "纽伦堡": ("Nuremberg", "德国", "Germany"),
    "莱比锡": ("Leipzig", "德国", "Germany"),
    "埃森": ("Essen", "德国", "Germany"),
    "腓特烈": ("Friedrichshafen", "德国", "Germany"),
    # 法国
    "巴黎": ("Paris", "法国", "France"),
    "里昂": ("Lyon", "法国", "France"),
    "马赛": ("Marseille", "法国", "France"),
    "戛纳": ("Cannes", "法国", "France"),
    "尼斯": ("Nice", "法国", "France"),
    "雷恩": ("Rennes", "法国", "France"),
    "拉罗谢尔": ("La Rochelle", "法国", "France"),
    # 意大利
    "米兰": ("Milan", "意大利", "Italy"),
    "罗马": ("Rome", "意大利", "Italy"),
    "博洛尼亚": ("Bologna", "意大利", "Italy"),
    "里米尼": ("Rimini", "意大利", "Italy"),
    "维琴察": ("Vicenza", "意大利", "Italy"),
    "维罗纳": ("Verona", "意大利", "Italy"),
    "都灵": ("Turin", "意大利", "Italy"),
    "佛罗伦萨": ("Florence", "意大利", "Italy"),
    "热那亚": ("Genoa", "意大利", "Italy"),
    "加达": ("Garda", "意大利", "Italy"),
    "贝加莫": ("Bergamo", "意大利", "Italy"),
    # 英国
    "伦敦": ("London", "英国", "United Kingdom"),
    "伯明翰": ("Birmingham", "英国", "United Kingdom"),
    "曼彻斯特": ("Manchester", "英国", "United Kingdom"),
    "切尔滕纳姆": ("Cheltenham", "英国", "United Kingdom"),
    "南安普顿": ("Southampton", "英国", "United Kingdom"),
    "切尔西": ("Chelsea", "英国", "United Kingdom"),
    # 日本
    "东京": ("Tokyo", "日本", "Japan"),
    "大阪": ("Osaka", "日本", "Japan"),
    "横滨": ("Yokohama", "日本", "Japan"),
    "名古屋": ("Nagoya", "日本", "Japan"),
    "神户": ("Kobe", "日本", "Japan"),
    "福冈": ("Fukuoka", "日本", "Japan"),
    "札幌": ("Sapporo", "日本", "Japan"),
    "九州": ("Kyushu", "日本", "Japan"),
    # 韩国
    "首尔": ("Seoul", "韩国", "South Korea"),
    "釜山": ("Busan", "韩国", "South Korea"),
    "光州": ("Gwangju", "韩国", "South Korea"),
    "仁川": ("Incheon", "韩国", "South Korea"),
    # 美国
    "拉斯维加斯": ("Las Vegas", "美国", "United States"),
    "纽约": ("New York", "美国", "United States"),
    "芝加哥": ("Chicago", "美国", "United States"),
    "洛杉矶": ("Los Angeles", "美国", "United States"),
    "旧金山": ("San Francisco", "美国", "United States"),
    "迈阿密": ("Miami", "美国", "United States"),
    "波士顿": ("Boston", "美国", "United States"),
    "华盛顿": ("Washington DC", "美国", "United States"),
    "亚特兰大": ("Atlanta", "美国", "United States"),
    "达拉斯": ("Dallas", "美国", "United States"),
    "休斯顿": ("Houston", "美国", "United States"),
    "西雅图": ("Seattle", "美国", "United States"),
    "奥兰多": ("Orlando", "美国", "United States"),
    "圣地亚哥": ("San Diego", "美国", "United States"),
    "丹佛": ("Denver", "美国", "United States"),
    "底特律": ("Detroit", "美国", "United States"),
    "费城": ("Philadelphia", "美国", "United States"),
    "纳什维尔": ("Nashville", "美国", "United States"),
    "圣何塞": ("San Jose", "美国", "United States"),
    "新奥尔良": ("New Orleans", "美国", "United States"),
    "盐湖城": ("Salt Lake City", "美国", "United States"),
    "安纳海姆": ("Anaheim", "美国", "United States"),
    "劳德代尔堡": ("Fort Lauderdale", "美国", "United States"),
    "罗利": ("Raleigh", "美国", "United States"),
    "马里科帕": ("Maricopa", "美国", "United States"),
    "诺维": ("Novi", "美国", "United States"),
    "赫尔希": ("Hershey", "美国", "United States"),
    "坦帕": ("Tampa", "美国", "United States"),
    # 俄罗斯
    "莫斯科": ("Moscow", "俄罗斯", "Russia"),
    "圣彼得堡": ("St. Petersburg", "俄罗斯", "Russia"),
    "乌法": ("Ufa", "俄罗斯", "Russia"),
    # 巴西
    "圣保罗": ("Sao Paulo", "巴西", "Brazil"),
    "里约": ("Rio de Janeiro", "巴西", "Brazil"),
    # 印度
    "孟买": ("Mumbai", "印度", "India"),
    "新德里": ("New Delhi", "印度", "India"),
    "班加罗尔": ("Bangalore", "印度", "India"),
    "海德拉巴": ("Hyderabad", "印度", "India"),
    "加尔各答": ("Kolkata", "印度", "India"),
    "金奈": ("Chennai", "印度", "India"),
    # 东南亚
    "曼谷": ("Bangkok", "泰国", "Thailand"),
    "胡志明": ("Ho Chi Minh", "越南", "Vietnam"),
    "河内": ("Hanoi", "越南", "Vietnam"),
    "雅加达": ("Jakarta", "印尼", "Indonesia"),
    "泗水": ("Surabaya", "印尼", "Indonesia"),
    "巴淡岛": ("Batam", "印尼", "Indonesia"),
    "棉兰": ("Medan", "印尼", "Indonesia"),
    "吉隆坡": ("Kuala Lumpur", "马来西亚", "Malaysia"),
    "槟城": ("Penang", "马来西亚", "Malaysia"),
    "马尼拉": ("Manila", "菲律宾", "Philippines"),
    "新加坡": ("Singapore", "新加坡", "Singapore"),
    "金边": ("Phnom Penh", "柬埔寨", "Cambodia"),
    # 中东
    "利雅得": ("Riyadh", "沙特", "Saudi Arabia"),
    "吉达": ("Jeddah", "沙特", "Saudi Arabia"),
    "马斯喀特": ("Muscat", "阿曼", "Oman"),
    "多哈": ("Doha", "卡塔尔", "Qatar"),
    "德黑兰": ("Tehran", "伊朗", "Iran"),
    "伊斯坦布尔": ("Istanbul", "土耳其", "Turkey"),
    "安卡拉": ("Ankara", "土耳其", "Turkey"),
    # 东欧/中亚
    "华沙": ("Warsaw", "波兰", "Poland"),
    "波兹南": ("Poznan", "波兰", "Poland"),
    "凯尔采": ("Kielce", "波兰", "Poland"),
    "布达佩斯": ("Budapest", "匈牙利", "Hungary"),
    "布拉格": ("Prague", "捷克", "Czech Republic"),
    "布加勒斯特": ("Bucharest", "罗马尼亚", "Romania"),
    "索非亚": ("Sofia", "保加利亚", "Bulgaria"),
    "基辅": ("Kiev", "乌克兰", "Ukraine"),
    "明斯克": ("Minsk", "白俄罗斯", "Belarus"),
    "塔什干": ("Tashkent", "乌兹别克斯坦", "Uzbekistan"),
    "阿拉木图": ("Almaty", "哈萨克斯坦", "Kazakhstan"),
    "阿斯塔纳": ("Astana", "哈萨克斯坦", "Kazakhstan"),
    "阿克托别": ("Aktobe", "哈萨克斯坦", "Kazakhstan"),
    "阿什哈巴德": ("Ashgabat", "土库曼斯坦", "Turkmenistan"),
    "巴库": ("Baku", "阿塞拜疆", "Azerbaijan"),
    # 欧洲其他
    "巴塞罗那": ("Barcelona", "西班牙", "Spain"),
    "马德里": ("Madrid", "西班牙", "Spain"),
    "阿姆斯特丹": ("Amsterdam", "荷兰", "Netherlands"),
    "鹿特丹": ("Rotterdam", "荷兰", "Netherlands"),
    "布鲁塞尔": ("Brussels", "比利时", "Belgium"),
    "日内瓦": ("Geneva", "瑞士", "Switzerland"),
    "苏黎世": ("Zurich", "瑞士", "Switzerland"),
    "维也纳": ("Vienna", "奥地利", "Austria"),
    "斯德哥尔摩": ("Stockholm", "瑞典", "Sweden"),
    "哥本哈根": ("Copenhagen", "丹麦", "Denmark"),
    "赫尔辛基": ("Helsinki", "芬兰", "Finland"),
    "奥斯陆": ("Oslo", "挪威", "Norway"),
    "里斯本": ("Lisbon", "葡萄牙", "Portugal"),
    "雅典": ("Athens", "希腊", "Greece"),
    "里加": ("Riga", "拉脱维亚", "Latvia"),
    # 非洲
    "开罗": ("Cairo", "埃及", "Egypt"),
    "约翰内斯堡": ("Johannesburg", "南非", "South Africa"),
    "开普敦": ("Cape Town", "南非", "South Africa"),
    "德班": ("Durban", "南非", "South Africa"),
    "内罗毕": ("Nairobi", "肯尼亚", "Kenya"),
    "卡萨布兰卡": ("Casablanca", "摩洛哥", "Morocco"),
    "拉各斯": ("Lagos", "尼日利亚", "Nigeria"),
    "阿布贾": ("Abuja", "尼日利亚", "Nigeria"),
    "达喀尔": ("Dakar", "塞内加尔", "Senegal"),
    "阿尔及尔": ("Algiers", "阿尔及利亚", "Algeria"),
    "达累斯萨拉姆": ("Dar es Salaam", "坦桑尼亚", "Tanzania"),
    "亚的斯亚贝巴": ("Addis Ababa", "埃塞俄比亚", "Ethiopia"),
    "阿克拉": ("Accra", "加纳", "Ghana"),
    # 美洲其他
    "多伦多": ("Toronto", "加拿大", "Canada"),
    "温哥华": ("Vancouver", "加拿大", "Canada"),
    "蒙特利尔": ("Montreal", "加拿大", "Canada"),
    "墨西哥城": ("Mexico City", "墨西哥", "Mexico"),
    "波哥大": ("Bogota", "哥伦比亚", "Columbia"),
    "麦德林": ("Medellin", "哥伦比亚", "Columbia"),
    "圣地亚哥(智利)": ("Santiago", "智利", "Chile"),
    "布宜诺斯艾利斯": ("Buenos Aires", "阿根廷", "Argentina"),
    "利马": ("Lima", "秘鲁", "Peru"),
    "基多": ("Quito", "厄瓜多尔", "Ecuador"),
    "巴拿马城": ("Panama City", "巴拿马", "Panama"),
    # 大洋洲
    "悉尼": ("Sydney", "澳大利亚", "Australia"),
    "墨尔本": ("Melbourne", "澳大利亚", "Australia"),
    "布里斯班": ("Brisbane", "澳大利亚", "Australia"),
    "珀斯": ("Perth", "澳大利亚", "Australia"),
    "阿德莱德": ("Adelaide", "澳大利亚", "Australia"),
    "黄金海岸": ("Gold Coast", "澳大利亚", "Australia"),
    "奥克兰": ("Auckland", "新西兰", "New Zealand"),
    "惠灵顿": ("Wellington", "新西兰", "New Zealand"),
    # 其他
    "乌兰巴托": ("Ulaanbaatar", "蒙古", "Mongolia"),
    "加德满都": ("Kathmandu", "尼泊尔", "Nepal"),
    "达卡": ("Dhaka", "孟加拉", "Bangladesh"),
    "科伦坡": ("Colombo", "斯里兰卡", "Sri Lanka"),
    "仰光": ("Yangon", "缅甸", "Myanmar"),
    "卡拉奇": ("Karachi", "巴基斯坦", "Pakistan"),
    "拉合尔": ("Lahore", "巴基斯坦", "Pakistan"),
    "伊斯兰堡": ("Islamabad", "巴基斯坦", "Pakistan"),
    "撒马尔罕": ("Samarkand", "乌兹别克斯坦", "Uzbekistan"),
    "摩纳哥": ("Monaco", "摩纳哥", "Monaco"),
}

# ============================================================
# 国家中文名（无城市）→ (country_en)
# 用于名称中只含国家名不含城市名的情况
# ============================================================
COUNTRIES_CN = {
    "中国": "China",
    "美国": "United States",
    "日本": "Japan",
    "德国": "Germany",
    "俄罗斯": "Russia",
    "印尼": "Indonesia",
    "印度尼西亚": "Indonesia",
    "越南": "Vietnam",
    "英国": "United Kingdom",
    "印度": "India",
    "韩国": "South Korea",
    "巴西": "Brazil",
    "泰国": "Thailand",
    "澳大利亚": "Australia",
    "澳洲": "Australia",
    "阿联酋": "UAE",
    "意大利": "Italy",
    "波兰": "Poland",
    "马来西亚": "Malaysia",
    "墨西哥": "Mexico",
    "法国": "France",
    "沙特": "Saudi Arabia",
    "沙特阿拉伯": "Saudi Arabia",
    "土耳其": "Turkey",
    "新加坡": "Singapore",
    "西班牙": "Spain",
    "南非": "South Africa",
    "菲律宾": "Philippines",
    "加拿大": "Canada",
    "埃及": "Egypt",
    "荷兰": "Netherlands",
    "瑞士": "Switzerland",
    "瑞典": "Sweden",
    "挪威": "Norway",
    "丹麦": "Denmark",
    "芬兰": "Finland",
    "比利时": "Belgium",
    "奥地利": "Austria",
    "希腊": "Greece",
    "葡萄牙": "Portugal",
    "爱尔兰": "Ireland",
    "捷克": "Czech Republic",
    "匈牙利": "Hungary",
    "罗马尼亚": "Romania",
    "保加利亚": "Bulgaria",
    "克罗地亚": "Croatia",
    "塞尔维亚": "Serbia",
    "乌克兰": "Ukraine",
    "白俄罗斯": "Belarus",
    "立陶宛": "Lithuania",
    "拉脱维亚": "Latvia",
    "爱沙尼亚": "Estonia",
    "斯洛文尼亚": "Slovenia",
    "斯洛伐克": "Slovakia",
    "哈萨克斯坦": "Kazakhstan",
    "乌兹别克斯坦": "Uzbekistan",
    "土库曼斯坦": "Turkmenistan",
    "塔吉克斯坦": "Tajikistan",
    "吉尔吉斯斯坦": "Kyrgyzstan",
    "阿塞拜疆": "Azerbaijan",
    "格鲁吉亚": "Georgia",
    "亚美尼亚": "Armenia",
    "蒙古": "Mongolia",
    "朝鲜": "North Korea",
    "缅甸": "Myanmar",
    "老挝": "Laos",
    "柬埔寨": "Cambodia",
    "文莱": "Brunei",
    "东帝汶": "East Timor",
    "尼泊尔": "Nepal",
    "不丹": "Bhutan",
    "孟加拉": "Bangladesh",
    "斯里兰卡": "Sri Lanka",
    "马尔代夫": "Maldives",
    "巴基斯坦": "Pakistan",
    "阿富汗": "Afghanistan",
    "伊朗": "Iran",
    "伊拉克": "Iraq",
    "科威特": "Kuwait",
    "阿曼": "Oman",
    "卡塔尔": "Qatar",
    "巴林": "Bahrain",
    "也门": "Yemen",
    "约旦": "Jordan",
    "黎巴嫩": "Lebanon",
    "叙利亚": "Syria",
    "以色列": "Israel",
    "巴勒斯坦": "Palestine",
    "摩洛哥": "Morocco",
    "阿尔及利亚": "Algeria",
    "突尼斯": "Tunisia",
    "利比亚": "Libya",
    "苏丹": "Sudan",
    "南苏丹": "South Sudan",
    "埃塞俄比亚": "Ethiopia",
    "肯尼亚": "Kenya",
    "坦桑尼亚": "Tanzania",
    "乌干达": "Uganda",
    "卢旺达": "Rwanda",
    "尼日利亚": "Nigeria",
    "加纳": "Ghana",
    "科特迪瓦": "Cote d'Ivoire",
    "塞内加尔": "Senegal",
    "喀麦隆": "Cameroon",
    "安哥拉": "Angola",
    "莫桑比克": "Mozambique",
    "津巴布韦": "Zimbabwe",
    "赞比亚": "Zambia",
    "博茨瓦纳": "Botswana",
    "纳米比亚": "Namibia",
    "刚果": "Congo",
    "加蓬": "Gabon",
    "阿根廷": "Argentina",
    "智利": "Chile",
    "秘鲁": "Peru",
    "哥伦比亚": "Colombia",
    "委内瑞拉": "Venezuela",
    "厄瓜多尔": "Ecuador",
    "玻利维亚": "Bolivia",
    "巴拉圭": "Paraguay",
    "乌拉圭": "Uruguay",
    "古巴": "Cuba",
    "巴拿马": "Panama",
    "哥斯达黎加": "Costa Rica",
    "危地马拉": "Guatemala",
    "洪都拉斯": "Honduras",
    "萨尔瓦多": "El Salvador",
    "尼加拉瓜": "Nicaragua",
    "牙买加": "Jamaica",
    "巴哈马": "Bahamas",
    "新西兰": "New Zealand",
    "斐济": "Fiji",
    "巴布亚新几内亚": "Papua New Guinea",
    "摩纳哥": "Monaco",
    "卢森堡": "Luxembourg",
    "马耳他": "Malta",
    "塞浦路斯": "Cyprus",
    "冰岛": "Iceland",
    "列支敦士登": "Liechtenstein",
    "安道尔": "Andorra",
    "圣马力诺": "San Marino",
    "梵蒂冈": "Vatican",
    "阿尔巴尼亚": "Albania",
    "波黑": "Bosnia and Herzegovina",
    "黑山": "Montenegro",
    "北马其顿": "North Macedonia",
    "摩尔多瓦": "Moldova",
}

# Non-country geo terms that should NOT match as country
NON_COUNTRY_TERMS = {
    "欧洲", "亚洲", "非洲", "美洲", "大洋洲", "北美", "南美",
    "中东", "东南亚", "东亚", "南亚", "中亚", "东欧", "西欧",
    "北欧", "拉美", "亚太", "东盟", "国际", "世界", "全球",
    "地中海", "加勒比", "波罗的海", "巴尔干", "斯堪的纳维亚",
}

# ============================================================
# 推理规则：完全无 geo 信息时的国家推断
# ============================================================
